### ISSUE TITLE
Problem 202

### ISSUE THREAD

**Issue by alimert2209** [alimert2209/LeetCode#5]
https://leetcode.com/problems/happy-number/

**Comment by AybenGulnar** [comment]
toplam 89'ken mutlu sayı olamıyor. O yüzdeen : 

class Solution {
       public boolean isHappy(int n) {
        int q,r,ans = 0;
        while(n!=89&&n!=1){
            ans = 0;
            while(n!=0){
            r = n%10;
            n = n/10;
            ans+=r*r;
            }
            n = ans;
        }
        return n==1?true:false;
    }

}
